export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const GET_PROJECT = "GET_PROJECT";
export const SEARCH_PROJECTS = "SEARCH_PROJECTS";
export const EDIT_PROJECT_IMAGE = "EDIT_PROJECT_IMAGE";
export const UPDATE_PROJECT_IMAGE_SRC = "UPDATE_PROJECT_IMAGE_SRC";

export const SET_USER = "SET_USER";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_SPECIFIED_USER_DATA = "GET_SPECIFIED_USER_DATA";
