export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const GET_PROJECT = "GET_PROJECT";
export const SEARCH_PROJECTS = "SEARCH_PROJECTS";
export const EDIT_PROJECT_IMAGE = "EDIT_PROJECT_IMAGE";
export const UPDATE_PROJECT_IMAGE_SRC = "UPDATE_PROJECT_IMAGE_SRC";
export const EDIT_PROJECT_IMAGE_ERROR = "EDIT_PROJECT_IMAGE_ERROR";
export const CLEAR_PROJECT_ERROR = "CLEAR_PROJECT_ERROR";

export const SET_USER = "SET_USER";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_SPECIFIED_USER_DATA = "GET_SPECIFIED_USER_DATA";

export const GET_PROJECT_COLLABORATORS = "GET_PROJECT_COLLABORATORS";
export const GET_PROJECT_COLLABORATORS_ERROR =
  "GET_PROJECT_COLLABORATORS_ERROR";

export const ADD_JOIN_APPLICATION = "ADD_JOIN_APPLICATION";
export const ADD_JOIN_APPLICATION_ERROR = "ADD_JOIN_APPLICATION_ERROR";
export const GET_JOIN_APPLICATIONS = "GET_JOIN_APPLICATIONS";
export const GET_JOIN_APPLICATIONS_ERROR = "GET_JOIN_APPLICATIONS_ERROR";
export const GET_JOIN_APPLICATION = "GET_JOIN_APPLICATION";
export const GET_JOIN_APPLICATION_ERROR = "GET_JOIN_APPLICATION_ERROR";
export const ACCEPT_JOIN_APPLICATION = "ACCEPT_JOIN_APPLICATION";
export const ACCEPT_JOIN_APPLICATION_ERROR = "ACCEPT_JOIN_APPLICATION_ERROR";
